-- LibCodex-1.0 / Data / Races.lua
-- Generated by tools/bake.py. 26 entries in unified row format.
-- Each row is a positional array matching the columns string below.
-- Hand-curated entries marked _handcrafted=true are preserved across bakes.

local LibCodex = LibStub("LibCodex-1.0")

LibCodex:_FeedBundledRowsLazy("Races", "id,label,token,side,playable,allied,sources", function() return {
    {1,"Human","Human","A",true,false,{"wago"}},
    {2,"Orc","Orc","H",true,false,{"wago"}},
    {3,"Dwarf","Dwarf","B",true,false,{"wago"}},
    {4,"Night Elf","NightElf","B",true,false,{"wago"}},
    {5,"Undead","Scourge","B",true,false,{"wago"}},
    {6,"Tauren","Tauren","B",true,false,{"wago"}},
    {7,"Gnome","Gnome","B",true,false,{"wago"}},
    {8,"Troll","Troll","B",true,false,{"wago"}},
    {9,"Goblin","Goblin","B",true,false,{"wago"}},
    {10,"Blood Elf","BloodElf","B",true,false,{"wago"}},
    {11,"Draenei","Draenei","B",true,false,{"wago"}},
    {12,"Fel Orc","FelOrc","A",false,false,{"wago"}},
    {13,"Naga","Naga_","A",false,false,{"wago"}},
    {14,"Broken","Broken","A",false,false,{"wago"}},
    {15,"Skeleton","Skeleton","A",false,false,{"wago"}},
    {16,"Vrykul","Vrykul","A",false,false,{"wago"}},
    {17,"Tuskarr","Tuskarr","A",false,false,{"wago"}},
    {18,"Forest Troll","ForestTroll","A",false,false,{"wago"}},
    {19,"Taunka","Taunka","A",false,false,{"wago"}},
    {20,"Northrend Skeleton","NorthrendSkeleton","A",false,false,{"wago"}},
    {21,"Ice Troll","IceTroll","A",false,false,{"wago"}},
    {22,"Worgen","Worgen","B",true,false,{"wago"}},
    {23,"Gilnean","Human","A",false,false,{"wago"}},
    {24,"Pandaren","Pandaren","B",true,false,{"wago"}},
    {25,"Pandaren","Pandaren","B",true,false,{"wago"}},
    {26,"Pandaren","Pandaren","B",true,false,{"wago"}},
} end)
