-- LibCodex-1.0 / Data / AchievementCategories.lua
-- Generated by tools/bake.py. 3 entries in unified row format.
-- Each row is a positional array matching the columns string below.
-- Hand-curated entries marked _handcrafted=true are preserved across bakes.

local LibCodex = LibStub("LibCodex-1.0")

LibCodex:_FeedBundledRowsLazy("AchievementCategories", "id,label,parentID,sources,uiOrder", function() return {
    {1,"Statistics",-1,{"wago"},1},
    {81,"Feats of Strength",-1,{"wago"},3},
    {15452,"BCC",-1,{"wago"},2},
} end)
