-- LibCodex-1.0 / Data / Battlemasters.lua
-- Generated by tools/bake.py. 12 entries in unified row format.
-- Each row is a positional array matching the columns string below.
-- Hand-curated entries marked _handcrafted=true are preserved across bakes.

local LibCodex = LibStub("LibCodex-1.0")

LibCodex:_FeedBundledRowsLazy("Battlemasters", "id,label,icon,flags,sources,gameType,instanceType,longDesc,maxGroupSize,maxLevel,maxPlayers,minLevel,minPlayers,pvpType,ratedPlayers,shortDesc", function() return {
    {1,"Alterac Valley",0,0,{"wago"},nil,0,"Hidden within the Alterac Mountains, Alterac Valley is the home of Thrall's own clan of orcs, the Frostwolves. The Stormpike dwarves have established a foothold in the valley and seek to plumb its depths for riches, and links to their ancestral past. The territorial Frostwolves, unwilling to suffer the dwarven incursion, have rallied an army... an army eager for righteous slaughter.",5,70,40,51,10,nil,0,"Hidden within the Alterac Mountains, Alterac Valley is the home of Thrall's own clan of orcs, the Frostwolves. The Stormpike dwarves have established a foothold in the valley and seek to plumb its depths for riches, and links to their ancestral past. The territorial Frostwolves, unwilling to suffer the dwarven incursion, have rallied an army... an army eager for righteous slaughter."},
    {2,"Warsong Gulch",0,8,{"wago"},nil,0,"A valley bordering Ashenvale Forest and the Barrens, Warsong Gulch hosts a constant battle between the Horde and the Alliance. Orcs use their Warsong Mill to cut lumber reaped from Ashenvale, provoking the night elves of Silverwing Hold. Eager to aid their allies, members of every race in Azeroth rush to the Gulch to lend sword, or spell, to the conflict.",10,70,10,10,5,nil,0,"A valley bordering Ashenvale Forest and the Barrens, Warsong Gulch hosts a constant battle between the Horde and the Alliance. Orcs use their Warsong Mill to cut lumber reaped from Ashenvale, provoking the night elves of Silverwing Hold. Eager to aid their allies, members of every race in Azeroth rush to the Gulch to lend sword, or spell, to the conflict."},
    {3,"Arathi Basin",0,8,{"wago"},nil,0,"The Arathi Basin is one of the main staging points of war between the Humans and the Forsaken in Azeroth. The League of Arathor seek to reclaim lost lands for their benefactors in Stormwind, while the Defilers – elite troopers under the watchful eye of Varimathras – seek to sever the vital connection between the Humans and their Dwarven allies to the south.",15,70,15,20,8,nil,0,"The Arathi Basin is one of the main staging points of war between the Humans and the Forsaken in Azeroth. The League of Arathor seek to reclaim lost lands for their benefactors in Stormwind, while the Defilers – elite troopers under the watchful eye of Varimathras – seek to sever the vital connection between the Humans and their Dwarven allies to the south."},
    {4,"Nagrand Arena",0,8,{"wago"},nil,1,nil,5,70,5,10,0,nil,0},
    {5,"Blade's Edge Arena",0,8,{"wago"},nil,1,nil,5,70,5,10,0,nil,0},
    {6,"All Arenas",0,8,{"wago"},nil,1,"Let the games begin! The door is open to all who wish to find glory in the arena, and the Steamwheedle Cartel is prepared to accept your entry into the games. If victory is your destiny, then register a team with an Arena Organizer, or join one that has already been registered!",5,70,5,10,0,nil,0},
    {7,"Eye of the Storm",0,8,{"wago"},nil,0,"Hovering high above the ravaged landscape of Netherstorm is the island known as the Eye of the Storm.  This battlefield is coveted by the blood elves for its rich energy deposits - and the draenei seek to claim it due to its proximity to the naaru's mysterious vessel - Tempest Keep.",15,70,15,61,8,nil,0},
    {8,"Ruins of Lordaeron",0,24,{"wago"},nil,1,nil,5,70,5,10,0,nil,0},
    {1043,"Blade's Edge Arena",0,24,{"wago"},nil,1,nil,0,0,5,0,1,nil,0},
    {1044,"Nagrand Arena",0,24,{"wago"},nil,1,nil,0,0,5,0,1,nil,0},
    {1045,"Eye of the Storm",0,8,{"wago"},nil,0,nil,15,0,15,0,8,nil,0},
    {1046,"Ruins of Lordaeron",0,24,{"wago"},nil,1,nil,0,0,5,0,1,nil,0},
} end)
