-- LibCodex-1.0 / Data / Currencies.lua
-- Generated by tools/bake.py. 2 entries in unified row format.
-- Each row is a positional array matching the columns string below.
-- Hand-curated entries marked _handcrafted=true are preserved across bakes.

local LibCodex = LibStub("LibCodex-1.0")

LibCodex:_FeedBundledRowsLazy("Currencies", "id,label,categoryID,sources,categoryName", function() return {
    {1900,"Arena Points",247,{"wago"},"Player vs. Player"},
    {1901,"Honor Points",247,{"wago"},"Player vs. Player"},
} end)
