-- LibCodex-1.0 / Data / Movies.lua
-- Generated by tools/bake.py. 3 entries in unified row format.
-- Each row is a positional array matching the columns string below.
-- Hand-curated entries marked _handcrafted=true are preserved across bakes.

local LibCodex = LibStub("LibCodex-1.0")

LibCodex:_FeedBundledRowsLazy("Movies", "id,sources,audioFileDataID,keyID,subtitleFileDataID,subtitleFileFormat,volume", function() return {
    {1,{"wago"},625988,0,0,nil,100},
    {2,{"wago"},625564,0,481154,nil,100},
    {27,{"wago"},625565,0,481145,nil,100},
} end)
