-- LibCodex-1.0 / Data / SpellRanges.lua
-- Generated by tools/bake.py. 35 entries in unified row format.
-- Each row is a positional array matching the columns string below.
-- Hand-curated entries marked _handcrafted=true are preserved across bakes.

local LibCodex = LibStub("LibCodex-1.0")

LibCodex:_FeedBundledRowsLazy("SpellRanges", "id,label,flags,sources,rangeMaxFriend,rangeMaxHostile,rangeMinFriend,rangeMinHostile,shortLabel", function() return {
    {1,"Self Only",0,{"wago"},0,0,0,0,"Self"},
    {2,"Combat Range",1,{"wago"},5,5,0,0,"Combat"},
    {3,"Twenty yards",0,{"wago"},20,20,0,0,"Short"},
    {4,"Medium Range",0,{"wago"},30,30,0,0,"Medium"},
    {5,"Long Range",0,{"wago"},40,40,0,0,"Long"},
    {6,"Vision Range",0,{"wago"},100,100,0,0,"Vision"},
    {7,"Ten yards",0,{"wago"},10,10,0,0,"Very Short"},
    {8,"Min Range 10, 20",0,{"wago"},20,20,10,10,"Short"},
    {9,"Medium Range",0,{"wago"},30,30,10,10,"Medium"},
    {10,"10-40",0,{"wago"},40,40,10,10,"Long"},
    {11,"Fifteen yards",0,{"wago"},15,15,0,0,"Shorter"},
    {12,"Interact Range",0,{"wago"},5,5,0,0,"Interact"},
    {13,"Anywhere - Unlimited",0,{"wago"},50000,50000,0,0,"Anywhere - Unlimited"},
    {14,"Extra Long Range",0,{"wago"},60,60,0,0,"Extra Long"},
    {34,"Twenty-Five yards",0,{"wago"},25,25,0,0,"Medium-Short"},
    {35,"Medium-Long Range",0,{"wago"},35,35,0,0,"Medium-Long"},
    {36,"Longer Range",0,{"wago"},45,45,0,0,"Longer"},
    {37,"Extended Range",0,{"wago"},50,50,0,0,"Extended"},
    {38,"Min-Range 10, 25",0,{"wago"},25,25,10,10,"Extra Medium"},
    {54,"Monster Shoot",0,{"wago"},30,30,5,5,"Monster Shoot Range"},
    {74,"Ranged Weapon",2,{"wago"},30,30,0,0,"Ranged"},
    {94,"Sting",0,{"wago"},40,40,8,8,"Sting"},
    {95,"Charge",0,{"wago"},25,25,8,8,"Charge"},
    {96,"Trap",0,{"wago"},2,2,0,0,"Trap"},
    {114,"Hunter Range",2,{"wago"},35,35,0,0,"Hunter"},
    {134,"Tower 80",0,{"wago"},80,80,0,0,"Tower"},
    {135,"Tower 100",0,{"wago"},100,100,0,0,"Tower"},
    {136,"Thirty-to-80",0,{"wago"},80,80,30,30,"Thirty-to-80"},
    {137,"Eight yards",0,{"wago"},8,8,0,0,"Very Short"},
    {138,"Long Range Hunter Shoot",0,{"wago"},45,45,5,5,"Hunter Long"},
    {140,"Six yards",0,{"wago"},7,7,0,0,"Six yards"},
    {141,"Seven yards",0,{"wago"},7,7,0,0,"Seven yards"},
    {151,"Long Range Hunter Shoot",0,{"wago"},45,45,5,5,"Hunter 45"},
    {155,"Hunter Range (Long)",0,{"wago"},35,35,4.0100,4.0100,"Hunter (Long)"},
    {157,"Ninety",0,{"wago"},90,90,0,0,"Ninety"},
} end)
