-- LibCodex-1.0 / Data / Movies.lua
-- Generated by tools/bake.py. 27 entries in unified row format.
-- Each row is a positional array matching the columns string below.
-- Hand-curated entries marked _handcrafted=true are preserved across bakes.

local LibCodex = LibStub("LibCodex-1.0")

LibCodex:_FeedBundledRowsLazy("Movies", "id,sources,audioFileDataID,keyID,subtitleFileDataID,subtitleFileFormat,volume", function() return {
    {1,{"wago"},625988,0,0,nil,100},
    {2,{"wago"},625564,0,481154,nil,100},
    {14,{"wago"},458394,0,481156,nil,100},
    {16,{"wago"},625989,0,512108,nil,100},
    {18,{"wago"},457498,0,462899,nil,250},
    {21,{"wago"},455940,8,481159,nil,100},
    {22,{"wago"},452603,9,463770,nil,100},
    {23,{"wago"},455939,10,481144,nil,100},
    {27,{"wago"},625565,0,481145,nil,100},
    {32,{"wago"},455940,8,481159,nil,100},
    {33,{"wago"},452603,9,463770,nil,100},
    {73,{"wago"},576955,35,0,nil,100},
    {74,{"wago"},576956,36,0,nil,100},
    {75,{"wago"},576957,37,0,nil,100},
    {76,{"wago"},577085,33,577086,nil,100},
    {115,{"wago"},644071,45,644072,nil,100},
    {116,{"wago"},644124,46,0,nil,100},
    {117,{"wago"},644128,47,644129,nil,100},
    {118,{"wago"},644134,48,644135,nil,100},
    {119,{"wago"},644136,49,644137,nil,100},
    {120,{"wago"},644138,50,644139,nil,100},
    {121,{"wago"},654949,52,0,nil,100},
    {123,{"wago"},644124,46,0,nil,100},
    {127,{"wago"},668414,0,0,nil,100},
    {128,{"wago"},668416,0,0,nil,100},
    {151,{"wago"},916419,57,916420,nil,100},
    {152,{"wago"},916417,56,916418,nil,100},
} end)
