-- LibCodex import from Blizzard Game Data API.
-- Generated by tools/import-blizzard.py.
-- Feed this into bake.py to merge into Data_<flavor>/*.lua.

LibCodexDB = {
    version = 1,
    modules = {
        NPCs = {}
    }
}
