-- LibCodex-1.0 / Data / Talents.lua
-- Generated by tools/bake.py. 9 entries in unified row format.
-- Each row is a positional array matching the columns string below.
-- Hand-curated entries marked _handcrafted=true are preserved across bakes.

local LibCodex = LibStub("LibCodex-1.0")

LibCodex:_FeedBundledRowsLazy("Talents", "id,spellID,sources", function() return {
    {133102,11210,{"wago"}},
    {133103,11222,{"wago"}},
    {133104,11237,{"wago"}},
    {133105,11069,{"wago"}},
    {133106,11103,{"wago"}},
    {133107,11189,{"wago"}},
    {133108,11070,{"wago"}},
    {133109,29438,{"wago"}},
    {133110,6057,{"wago"}},
} end)
