-- LibCodex-1.0 / Data / ChatChannels.lua
-- Generated by tools/bake.py. 6 entries in unified row format.
-- Each row is a positional array matching the columns string below.
-- Hand-curated entries marked _handcrafted=true are preserved across bakes.

local LibCodex = LibStub("LibCodex-1.0")

LibCodex:_FeedBundledRowsLazy("ChatChannels", "id,label,flags,sources,factionGroup,ruleset,shortcut", function() return {
    {1,"General - %s",524299,{"wago"},0,0,"General"},
    {2,"Trade - %s",59,{"wago"},0,0,"Trade"},
    {22,"LocalDefense - %s",65547,{"wago"},0,0,"LocalDefense"},
    {23,"WorldDefense",65540,{"wago"},0,0,"WorldDefense"},
    {26,"LookingForGroup",17039361,{"wago"},0,0,"LookingForGroup"},
    {45,"Services",50331648,{"wago"},0,0,"Services"},
} end)
