-- LibCodex-1.0 / Data / Difficulty.lua
-- Generated by tools/bake.py. 20 entries in unified row format.
-- Each row is a positional array matching the columns string below.
-- Hand-curated entries marked _handcrafted=true are preserved across bakes.

local LibCodex = LibStub("LibCodex-1.0")

LibCodex:_FeedBundledRowsLazy("Difficulty", "id,label,flags,sources,fallbackDifficultyID,instanceType,maxPlayers,minPlayers,orderIndex", function() return {
    {1,"Normal",6,{"wago"},0,1,5,5,1},
    {2,"Heroic",5,{"wago"},1,1,5,5,2},
    {3,"10 Player",6,{"wago"},0,2,10,10,1},
    {4,"25 Player",6,{"wago"},0,2,25,25,3},
    {5,"10 Player (Heroic)",5,{"wago"},3,2,10,10,2},
    {6,"25 Player (Heroic)",5,{"wago"},4,2,25,25,4},
    {7,"Looking For Raid",16,{"wago"},4,2,25,25,5},
    {8,"Challenge Mode",5,{"wago"},2,1,5,5,3},
    {9,"40 Player",0,{"wago"},0,2,40,40,7},
    {11,"Heroic Scenario",1,{"wago"},12,5,3,3,2},
    {12,"Normal Scenario",2,{"wago"},0,5,5,5,1},
    {14,"Flexible",16,{"wago"},0,2,25,10,6},
    {148,"20 Player",0,{"wago"},0,2,20,20,6},
    {173,"Normal",0,{"wago"},1,1,5,5,1},
    {174,"Heroic",1,{"wago"},2,1,5,5,3},
    {175,"10 Player",0,{"wago"},3,2,10,10,1},
    {176,"25 Player",0,{"wago"},4,2,25,25,3},
    {193,"10 Player (Heroic)",1,{"wago"},5,2,10,10,2},
    {194,"25 Player (Heroic)",1,{"wago"},6,2,25,25,4},
    {237,"Celestial",4,{"wago"},2,1,5,5,4},
} end)
