-- LibCodex-1.0 / Data / AchievementCategories.lua
-- Generated by tools/bake.py. 13 entries in unified row format.
-- Each row is a positional array matching the columns string below.
-- Hand-curated entries marked _handcrafted=true are preserved across bakes.

local LibCodex = LibStub("LibCodex-1.0")

LibCodex:_FeedBundledRowsLazy("AchievementCategories", "id,label,parentID,sources,uiOrder", function() return {
    {1,"Statistics",-1,{"wago"},4},
    {21,"Player vs. Player",1,{"wago"},1},
    {81,"Feats of Strength",-1,{"wago"},3},
    {168,"Dungeons & Raids",-1,{"wago"},2},
    {14807,"Dungeons & Raids",1,{"wago"},2},
    {14808,"Classic",168,{"wago"},1},
    {14821,"Classic",14807,{"wago"},1},
    {15228,"Draenor Dungeon",168,{"wago"},2},
    {15233,"Warlords of Draenor",14807,{"wago"},2},
    {15269,"Mounts",81,{"wago"},1},
    {15425,"_",-1,{"wago"},1},
    {15537,"Season of Discovery",-1,{"wago"},5},
    {15538,"Rune Discovery",15537,{"wago"},1},
} end)
