-- LibCodex-1.0 / Data / CreatureTypes.lua
-- Generated by tools/bake.py. 11 entries in unified row format.
-- Each row is a positional array matching the columns string below.
-- Hand-curated entries marked _handcrafted=true are preserved across bakes.

local LibCodex = LibStub("LibCodex-1.0")

LibCodex:_FeedBundledRowsLazy("CreatureTypes", "id,label,sources", function() return {
    {1,"Beast",{"wago"}},
    {2,"Dragonkin",{"wago"}},
    {3,"Demon",{"wago"}},
    {4,"Elemental",{"wago"}},
    {5,"Giant",{"wago"}},
    {6,"Undead",{"wago"}},
    {7,"Humanoid",{"wago"}},
    {8,"Critter",{"wago"}},
    {9,"Mechanical",{"wago"}},
    {10,"Not specified",{"wago"}},
    {11,"Totem",{"wago"}},
} end)
