-- LibCodex-1.0 / Data / Difficulty.lua
-- Generated by tools/bake.py. 18 entries in unified row format.
-- Each row is a positional array matching the columns string below.
-- Hand-curated entries marked _handcrafted=true are preserved across bakes.

local LibCodex = LibStub("LibCodex-1.0")

LibCodex:_FeedBundledRowsLazy("Difficulty", "id,label,flags,sources,fallbackDifficultyID,instanceType,maxPlayers,minPlayers,orderIndex", function() return {
    {1,"Normal",6,{"wago"},0,1,5,5,1},
    {9,"40 Player",1,{"wago"},0,2,40,40,7},
    {148,"20 Player",1,{"wago"},0,2,20,20,6},
    {184,"Normal",0,{"wago"},0,1,5,5,1},
    {185,"20 Player",1,{"wago"},0,2,20,20,6},
    {186,"40 Player",1,{"wago"},0,2,40,40,7},
    {197,"10 Player",1,{"wago"},0,2,10,10,8},
    {198,"Normal",1,{"wago"},0,1,10,10,1},
    {201,"Normal",0,{"wago"},0,1,5,5,1},
    {202,"Difficulty A",0,{"wago"},0,1,5,5,2},
    {203,"Difficulty B",0,{"wago"},0,1,5,5,3},
    {204,"Difficulty C",0,{"wago"},0,1,5,5,4},
    {207,"Normal",0,{"wago"},0,1,1,1,1},
    {213,"Infinite",0,{"wago"},0,1,5,5,1},
    {214,"DNT - Internal only",0,{"wago"},0,1,5,5,5},
    {215,"Normal",1,{"wago"},0,1,20,20,1},
    {226,"20 Player",1,{"wago"},0,2,20,20,6},
    {231,"Normal",0,{"wago"},0,2,1,1,1},
} end)
