-- LibCodex-1.0 / Data / GameObjects.lua
-- Generated by tools/bake.py. 14 entries in unified row format.
-- Each row is a positional array matching the columns string below.
-- Hand-curated entries marked _handcrafted=true are preserved across bakes.

local LibCodex = LibStub("LibCodex-1.0")

LibCodex:_FeedBundledRowsLazy("GameObjects", "id,label,sources,displayID,typeID", function() return {
    {1,"Felwood",{"wago"},388,5},
    {2719,"Hammerfall",{"wago"},195,5},
    {2784,"Felwood",{"wago"},386,5},
    {2790,"Magus Rimtori's Journal",{"wago"},254,5},
    {2806,"Ashenvale",{"wago"},388,5},
    {2807,"Monastery",{"wago"},27,5},
    {2817,"Kel'Theril",{"wago"},388,5},
    {2832,"Westfall",{"wago"},27,5},
    {2853,"Deadwind Pass",{"wago"},27,5},
    {2856,nil,{"wago"},100885,5},
    {2861,"Goldshire",{"wago"},26,5},
    {2868,nil,{"wago"},100885,5},
    {2875,"Abandon hope, all ye who enter here.",{"wago"},4651,5},
    {2908,nil,{"wago"},100879,5},
} end)
