-- LibCodex-1.0 / Data / NPCs.lua
-- Generated by tools/bake.py. 1 entries in unified row format.
-- Each row is a positional array matching the columns string below.
-- Hand-curated entries marked _handcrafted=true are preserved across bakes.

local LibCodex = LibStub("LibCodex-1.0")

LibCodex:_FeedBundledRowsLazy("NPCs", "id,label,creatureType,classification,sources", function() return {
    {61544,"Orphan Spell Visual Invisible Holder","Not specified","Normal",{"wago"}},
} end)
