-- LibCodex-1.0 / Data / Languages.lua
-- v2 compressed format. Generated by bake_v2/emit/module.py.
-- 45 entries, schema _V=1, _BUILD=120005.

local LibCodex = LibStub("LibCodex-1.0")

local _N = "Languages"
local _V, _BUILD = 1, 120005

LibCodex:_FeedBundledRowsV2(_N, _V, _BUILD, function() return {
    {1,"0z^-Cx(^}/",0,0,0,0},
    {2,"0yQvpzEEQcx<>(V",0,0,0,0},
    {3,"090xHA:-S)",0,0,0,0},
    {6,"14muwA=#erxAe2j",0,0,0,0},
    {7,"0yH^xzeTp(",0,0,0,0},
    {8,"07pynz/fo0",0,0,0,0},
    {9,"0-S(QvqV5B",0,0,0,0},
    {10,"0Ar-vy*?yax<>(V",0,0,0,0},
    {11,"14mfrv@Dm0v/MGe",0,0,0,0},
    {12,"083:px(do>",0,0,0,0},
    {13,"07Q{Bze168",0,0,0,0},
    {14,"09S/Gwmop*",0,0,0,0},
    {33,"14EiHB75&}zu6Up",0,0,0,0},
    {35,"07p<owO#6[",0,0,0,0},
    {36,"0A%zUvRGxN",0,0,0,0},
    {37,"0y}3Cze168avo^WvrcR[",0,0,0,0},
    {38,"0.mfry?W=fltpsCA^mS+",0,0,0,0},
    {39,"07Q:tzE)l]",0,0,0,0},
    {40,"0y}6qy?W+!",0,0,0,0},
    {42,"15JAzwmoH&zu6Up",0,0,0,0},
    {43,"15JAzwmoH&zu6Up",0,0,0,0},
    {44,"15JAzwmoH&zu6Up",0,0,0,0},
    {168,"0Ai@Tx()[^",0,0,0,0},
    {178,"0-J=vBz948vr8tF",0,0,0,0},
    {179,"15rAFxkzp6xAe2j",0,0,0,0},
    {180,"08mxIzFJ%7",0,0,0,0},
    {181,"0AiVuy*?yax<>(V",0,0,0,0},
    {182,"0Ar-vy*?yax<>(V",0,0,0,0},
    {285,"09jkUAaK5#",0,0,0,0},
    {287,"0yH^xAbo9gavx<ZxK#h:",0,0,0,0},
    {288,"143Bqx>5nMD2NCdASu7t",0,0,0,0},
    {290,"08m3DA+O@#",7,0,36,5410},
    {291,"13{:Bz/fn$zu6Up",7,0,36,5410},
    {292,"0-K2RA:-<1vqV5B",7,0,36,5410},
    {293,"0ypp9y?WwV",7,0,36,5410},
    {294,"0yQHcy?WwV",7,0,36,5410},
    {295,"15%qLvR6v&z2:Lo",7,0,36,5410},
    {296,"143BqB75)0z2:Lo",7,0,36,5410},
    {297,"0yZ<mwN]s.wfsMOzFa92xjVb:",2,0,0,0},
    {298,"0AB2MzF%-cvR/PQ",7,0,36,5410},
    {303,"07I9KvSc6}",1,62550,36,5508},
    {304,"07yspBzbl6",1,69564,36,0},
    {307,"15rAFBZ/5[zu6Up",0,0,0,0},
    {308,"15%hRxlv^baA7<mq^<MNBAI2jC(N*A",0,0,0,0},
    {309,"07ZKsvjb@b",0,0,0,0},
} end)
