-- LibCodex-1.0 / Data / Classes.lua
-- v2 compressed format. Generated by bake_v2/emit/module.py.
-- 15 entries, schema _V=1, _BUILD=120005.

local LibCodex = LibStub("LibCodex-1.0")

local _N = "Classes"
local _V, _BUILD = 1, 120005

LibCodex:_FeedBundledRowsV2(_N, _V, _BUILD, function() return {
    {1,"09rPHA+PDj","09qD:qB%UZ"},
    {2,"08N9uvpT7&","08L%Pk$1pt"},
    {3,"0z4uJBy/E)","0z3i=r7fW+"},
    {4,"0-A@HB.7KM","0-z/:ryD(/"},
    {5,"0z)/JwPI}[","0z(V=mn)d="},
    {6,"14lZeBz8^&zFr-%Bn#pv","07omwr7GUSnK(rJ"},
    {7,"0AiVuzddqZ","0AhJPo*IIO"},
    {8,"15iipwDhYg","15h6Kmf0q/"},
    {9,"09rPHy&r*0","09qD:oIX2G"},
    {10,"15iYKyxatm","15hM^o8[}("},
    {11,"0Z}6Kx>dhz","0Z]{^nKJKU"},
    {12,"14lZqz/cW*B-8qjASu7t","07omIpFKCXpe<UW"},
    {13,"0y.fIyH}I^","0yZ3+ogq.U"},
    {14,"0ypmtwO#QjA+fm>","0yoaOmnu/ZqBKE-"},
    {15,"15%qHC4CG3ASu7t","15@e:rZ/XJqucW%"},
} end)
