-- LibCodex-1.0 / Data / Stats.lua
-- v2 compressed format. Generated by bake_v2/emit/module.py.
-- 15 entries, schema _V=1, _BUILD=120005.

local LibCodex = LibStub("LibCodex-1.0")

local _N = "Stats"
local _V, _BUILD = 1, 120005

LibCodex:_FeedBundledRowsV2(_N, _V, _BUILD, function() return {
    {1,"15<qZwO#d5xAe2j","07*cUo<ZQ<l%&>(qBKtJr7Hv{nkAb.","0b#%)zddEg"},
    {2,"06$miy?X0p","0zclVo<ZQ<l%&kInLzYPsZL8#pF$c(","0b#%)zddEg"},
    {3,"0.EoKwO=f]v@}XJ","14=DXo<ZQ<l%&IXr7fFOmmg3Yq+fXZq#=)#","0b#%)zddEg"},
    {4,"08)#Fze0(@","0zclVo<ZQ<l%&>(k$%{Cl0)LYpF$c(","0b#%)zddEg"},
    {10,"07g^vBzkk[y-(U#A+Pr2","0zclVo<ZQ<l%&qVnMo4{k#ZAJm{/g=pF$c(","0=}{.z/f8]A^mS+"},
    {11,"0.u:vBy+BL","07*cUo<ZQ<l%&FJq=Dg)qBanNpdFU&nkAb.","0=}{.z/f8]A^mS+"},
    {12,"08l)yBy/Gr","0.DuWo<ZQ<l%&UOq=Dg-sZL5)r7P?PuSfG>qD9R@","0=}{.z/f8]A^mS+"},
    {13,"09iVKB76f8y?X0p","14=DXo<ZQ<l%&$-qD2>XnLzYPsPwB4","0=}{.z/f8]A^mS+"},
    {20,"0.^fpv}U&x","07*cUo<ZQ<l%&qVuRB3Xmn)eOk$>S:nkAb.","19w9{Bzkf7C(N*A"},
    {21,"0ZR0Fx>gT&v}tSu","07*cUo<ZQ<l%&qVuQmZ*nKL<tlQ+uXnkAb.","19w9{Bzkf7C(N*A"},
    {22,"0-K5HwN>=v","07*cUo<ZQ<l%&qVuSf=&mmpGYnkAb.","19w9{Bzkf7C(N*A"},
    {23,"0zdftwPI%lBZ]JcvR/PQ","14=DXo<ZQ<l%&qVuSf{7qBB8Kmn)b(q+fXZq#=)#","19w9{Bzkf7C(N*A"},
    {30,"0ZQ<zz/L*T","0zclVo<ZQ<l%&kTo&1T!","0+t>OwO#N6C4yTN"},
    {31,"0Z{%qxjR5y","0.DuWo<ZQ<l%&tTl}oWMqBanNpdCo:","0+t>OwO#N6C4yTN"},
    {32,"0-irCA^mS+","0.DuWo<ZQ<l%&+RqC{U8qBanNpdCo:","0+t>OwO#N6C4yTN"},
} end)
