-- LibCodex-1.0 / Data / Holidays.lua
-- Generated by tools/bake.py. 6 entries in unified row format.
-- Each row is a positional array matching the columns string below.
-- Hand-curated entries marked _handcrafted=true are preserved across bakes.

local LibCodex = LibStub("LibCodex-1.0")

LibCodex:_FeedBundledRowsLazy("Holidays", "id,region,flags,sources,descriptionID,filterType,looping,nameID,priority", function() return {
    {1193,528,14,{"wago"},0,0,0,0,0},
    {1223,784,14,{"wago"},0,0,0,0,0},
    {1318,2017,15,{"wago"},0,0,0,0,0},
    {1320,24,15,{"wago"},0,0,0,0,0},
    {1321,4,15,{"wago"},0,0,0,0,0},
    {1322,2,15,{"wago"},0,0,0,0,0},
} end)
