-- LibCodex-1.0 / Data / GameObjects.lua
-- Generated by tools/bake.py. 27 entries in unified row format.
-- Each row is a positional array matching the columns string below.
-- Hand-curated entries marked _handcrafted=true are preserved across bakes.

local LibCodex = LibStub("LibCodex-1.0")

LibCodex:_FeedBundledRowsLazy("GameObjects", "id,label,sources,displayID,typeID", function() return {
    {1,"The Sludge fen",{"wago"},308,5},
    {530,"Magisters' Terrace",{"wago"},6897,5},
    {560,"Tarren Mill",{"wago"},195,5},
    {571,nil,{"wago"},8053,5},
    {595,"Hearthglen",{"wago"},4531,5},
    {609,nil,{"wago"},8072,5},
    {648,"Slinky Sharpshiv's Crate",{"wago"},9057,5},
    {654,"Wahl Cottage",{"wago"},9137,5},
    {659,nil,{"wago"},9778,5},
    {661,"Tool Bucket",{"wago"},1211,5},
    {719,"Shrine of Aviana",{"wago"},388,5},
    {860,"Wu-Song Village",{"wago"},10885,5},
    {870,"Shredder 002",{"wago"},7835,5},
    {967,"Dragon Soul - Deathwing - Sunbeam Object",{"wago"},11090,5},
    {972,"Cho Family Shrine",{"wago"},11299,5},
    {974,"Merry-Go-Round!",{"wago"},9126,5},
    {999,"The Barrens",{"wago"},150,5},
    {1000,"The Barrens",{"wago"},150,5},
    {1024,"Dawn's Blossom",{"wago"},10885,5},
    {1030,"Broken Mogu Statue",{"wago"},11379,5},
    {1061,"Chair",{"wago"},138,5},
    {1064,"Sunreaver Ballista",{"wago"},13602,5},
    {1102,"Mailbox",{"wago"},2128,5},
    {1103,"Mailbox",{"wago"},7610,5},
    {1126,"Smelting Pot 02",{"wago"},13618,5},
    {2118,"Alliance Banner",{"wago"},8256,5},
    {2864,"Ruins of Guo-Lai",{"wago"},10885,5},
} end)
