-- LibCodex-1.0 / Data / Cinematics.lua
-- Generated by tools/bake.py. 27 entries in unified row format.
-- Each row is a positional array matching the columns string below.
-- Hand-curated entries marked _handcrafted=true are preserved across bakes.

local LibCodex = LibStub("LibCodex-1.0")

LibCodex:_FeedBundledRowsLazy("Cinematics", "id,sources,cameras,soundID", function() return {
    {1,{"wago"},{1},0},
    {2,{"wago"},{2},0},
    {21,{"wago"},{235},0},
    {41,{"wago"},{234},0},
    {61,{"wago"},{122},0},
    {81,{"wago"},{142},0},
    {101,{"wago"},{279},0},
    {121,{"wago"},{251},0},
    {141,{"wago"},{202},0},
    {161,{"wago"},{224},0},
    {162,{"wago"},{243},0},
    {163,{"wago"},{244},0},
    {164,{"wago"},{245},0},
    {165,{"wago"},{246},0},
    {167,{"wago"},{247},0},
    {168,{"wago"},{248},0},
    {169,{"wago"},{249},0},
    {170,{"wago"},{253},0},
    {172,{"wago"},{288},0},
    {173,{"wago"},{277},0},
    {197,{"wago"},{306},25450},
    {259,{"wago"},{343},0},
    {265,{"wago"},{345},0},
    {267,{"wago"},nil,0},
    {268,{"wago"},nil,0},
    {271,{"wago"},{356},0},
    {272,{"wago"},{355},0},
} end)
