-- LibCodex-1.0 / Data / Holidays.lua
-- Generated by tools/bake.py. 10 entries in unified row format.
-- Each row is a positional array matching the columns string below.
-- Hand-curated entries marked _handcrafted=true are preserved across bakes.

local LibCodex = LibStub("LibCodex-1.0")

LibCodex:_FeedBundledRowsLazy("Holidays", "id,region,flags,sources,descriptionID,filterType,looping,nameID,priority", function() return {
    {1193,528,14,{"wago"},0,0,0,0,0},
    {1223,784,14,{"wago"},0,0,0,0,0},
    {1498,0,34,{"wago"},0,0,0,0,0},
    {1544,0,34,{"wago"},0,0,0,0,0},
    {1579,833,3,{"wago"},0,0,1,0,0},
    {1580,24,3,{"wago"},0,0,1,0,0},
    {1581,4,3,{"wago"},0,0,1,0,0},
    {1582,2,3,{"wago"},0,0,1,0,0},
    {1596,768,15,{"wago"},0,0,0,0,0},
    {1597,768,14,{"wago"},0,0,0,0,0},
} end)
