-- LibCodex-1.0 / Data / Battlemasters.lua
-- Generated by tools/bake.py. 27 entries in unified row format.
-- Each row is a positional array matching the columns string below.
-- Hand-curated entries marked _handcrafted=true are preserved across bakes.

local LibCodex = LibStub("LibCodex-1.0")

LibCodex:_FeedBundledRowsLazy("Battlemasters", "id,label,icon,flags,sources,gameType,instanceType,longDesc,maxGroupSize,maxLevel,maxPlayers,minLevel,minPlayers,pvpType,ratedPlayers,shortDesc", function() return {
    {1,"Alterac Valley",136324,24,{"wago"},"Raid Battle",0,nil,10,90,40,45,10,nil,25},
    {2,"Warsong Gulch",136365,24,{"wago"},"Capture the Flag",0,nil,10,90,10,10,5,nil,10},
    {3,"Arathi Basin",136322,24,{"wago"},"Domination",0,nil,10,90,15,10,8,nil,10},
    {4,"Nagrand Arena",460867,8,{"wago"},nil,1,nil,5,90,5,10,0,nil,5},
    {5,"Blade's Edge Arena",460861,8,{"wago"},nil,1,nil,5,90,5,10,0,nil,5},
    {6,"All Arenas",525915,8,{"wago"},nil,1,nil,5,90,5,10,0,nil,5},
    {7,"Eye of the Storm",525912,24,{"wago"},"Domination",0,nil,10,90,15,35,8,nil,15},
    {8,"Ruins of Lordaeron",460869,8,{"wago"},nil,1,nil,5,90,5,10,0,nil,5},
    {9,"Strand of the Ancients",460870,24,{"wago"},"Siege",0,nil,10,90,15,65,8,nil,15},
    {10,"Dalaran Sewers",460862,8,{"wago"},nil,1,nil,5,90,5,10,0,nil,5},
    {11,"The Ring of Valor",460868,0,{"wago"},nil,1,nil,5,90,5,10,0,nil,5},
    {30,"Isle of Conquest",311222,24,{"wago"},"Raid Battle",0,nil,10,90,40,71,10,nil,25},
    {32,"Random Battleground",525915,24,{"wago"},nil,0,nil,10,90,40,45,5,nil,25},
    {100,"Rated Battleground",0,2,{"wago"},nil,0,nil,10,90,10,10,5,nil,10},
    {101,"Rated Battleground",0,2,{"wago"},nil,0,nil,15,90,15,20,8,nil,15},
    {102,"Rated Battleground",0,2,{"wago"},nil,0,nil,5,90,40,71,10,nil,25},
    {108,"Twin Peaks",525913,24,{"wago"},"Capture the Flag",0,nil,10,90,10,85,5,nil,10},
    {120,"The Battle for Gilneas",460871,24,{"wago"},"Domination",0,nil,10,90,10,85,5,nil,10},
    {656,"Rated Eye of the Storm",0,2,{"wago"},nil,0,nil,10,0,10,0,5,nil,10},
    {699,"Temple of Kotmogu",791651,24,{"wago"},"Power Orbs",0,nil,5,90,10,90,5,nil,10},
    {708,"Silvershard Mines",791650,24,{"wago"},"Payload",0,nil,5,90,10,90,5,nil,10},
    {719,"Tol'Viron Arena",791652,8,{"wago"},nil,1,nil,5,90,5,90,0,nil,5},
    {754,"Deepwind Gorge",875925,24,{"wago"},"Domination",0,nil,5,90,15,90,8,nil,10},
    {757,"The Tiger's Peak",875926,8,{"wago"},nil,1,nil,5,90,5,90,0,nil,5},
    {1089,"Wintergrasp",0,16,{"wago"},nil,0,nil,40,90,120,71,1,nil,0},
    {1116,"Battle for Tol Barad",0,16,{"wago"},nil,0,nil,40,90,80,85,1,nil,0},
    {1121,"The Battle for Gilneas (Old City Map)",0,0,{"wago"},nil,0,nil,10,0,10,0,5,nil,10},
} end)
