-- LibCodex-1.0 / Data / Cinematics.lua
-- Generated by tools/bake.py. 13 entries in unified row format.
-- Each row is a positional array matching the columns string below.
-- Hand-curated entries marked _handcrafted=true are preserved across bakes.

local LibCodex = LibStub("LibCodex-1.0")

LibCodex:_FeedBundledRowsLazy("Cinematics", "id,sources,cameras,soundID", function() return {
    {1,{"wago"},{1},0},
    {2,{"wago"},{2},0},
    {21,{"wago"},{235},0},
    {41,{"wago"},{234},0},
    {61,{"wago"},{122},0},
    {81,{"wago"},{142},0},
    {101,{"wago"},{162},0},
    {121,{"wago"},{182},0},
    {141,{"wago"},{202},0},
    {161,{"wago"},{224},0},
    {162,{"wago"},{243},0},
    {163,{"wago"},{244},0},
    {164,{"wago"},{245},0},
} end)
