-- LibCodex-1.0 / Data / Achievements.lua
-- Generated by tools/bake.py. 34 entries in unified row format.
-- Each row is a positional array matching the columns string below.
-- Hand-curated entries marked _handcrafted=true are preserved across bakes.

local LibCodex = LibStub("LibCodex-1.0")

LibCodex:_FeedBundledRowsLazy("Achievements", "id,label,side,categoryID,description,points,sources,categoryName,criteria,criteriaTree", function() return {
    {2716,"Dual Talent Specialization","B",81,"Visit your class trainer when you are at least level 40 and activate your Dual Talent Specialization.",0,{"wago"},"Feats of Strength",{{type="buy_quest",description="Learn a Second Talent Specialization.",amount=1,asset=63624,order=0},{type=5,description="Level up to 40.",amount=40,asset=0,order=1}},128587},
    {9275,"Warlord Zaela kills (Upper Blackrock Spire)","B",15233,nil,0,{"wago"},"Warlords of Draenor",nil,38168},
    {15329,"Has Died","B",14821,nil,0,{"wago"},"Classic",{{type=17,description=nil,amount=1,asset=0,order=0}},94296},
    {15330,"Survivor of the Firelord","B",14821,nil,0,{"wago"},"Classic",{{type="be_spell_target",description=nil,amount=1,asset=364095,order=0}},94292},
    {15332,"Survivor","B",14821,nil,0,{"wago"},"Classic",{{type=5,description=nil,amount=60,asset=0,order=0}},94307},
    {15333,"Survivor of the Shadow Flame","B",14821,nil,0,{"wago"},"Classic",{{type="be_spell_target",description=nil,amount=1,asset=364339,order=0}},94311},
    {15334,"Survivor of the Old God","B",14821,nil,0,{"wago"},"Classic",{{type="be_spell_target",description=nil,amount=1,asset=364340,order=0}},94313},
    {15335,"Survivor of the Damned","B",14821,nil,0,{"wago"},"Classic",{{type="be_spell_target",description=nil,amount=1,asset=364341,order=0}},94315},
    {15578,"<Hidden> Adventure Awaits - Hit 60 with Buff Adventure Awaits","B",14821,nil,0,{"wago"},"Classic",{{type=5,description=nil,amount=60,asset=0,order=0}},95385},
    {15637,"The Immortal","B",14808,nil,0,{"wago"},"Classic",{{type="kill_creature",description=nil,amount=0,asset=15990,order=0}},95610},
    {19563,"UNUSED Bael'Gar Defeated (Daily)","B",14821,nil,0,{"wago"},"Classic",nil,0},
    {20129,"[DNT] Discoverer's Delight - Reach Level 25 in Phase 2 (hidden)","B",81,nil,0,{"wago"},"Feats of Strength",{{type=5,description=nil,amount=25,asset=0,order=0}},156290},
    {20130,"[DNT] Discoverer's Delight - Reach Level 40 in Phase 3 (hidden)","B",81,nil,0,{"wago"},"Feats of Strength",{{type=5,description=nil,amount=40,asset=0,order=0}},157566},
    {20131,"[DNT] Discoverer's Delight - Reach Level 60 in Phase 4 (hidden)","B",81,nil,0,{"wago"},"Feats of Strength",{{type=5,description=nil,amount=60,asset=0,order=0}},161531},
    {20132,"[DNT] Discoverer's Delight - Reach Level 60 in Phase 5 (hidden)","B",81,nil,0,{"wago"},"Feats of Strength",{{type=5,description=nil,amount=60,asset=0,order=0}},156296},
    {20133,"[DNT] Self-Found Soul (Level 1)","B",81,nil,0,{"wago"},"Feats of Strength",nil,156298},
    {20134,"[DNT] Self-Found Soul (Level 10)","B",81,nil,0,{"wago"},"Feats of Strength",nil,156301},
    {20135,"[DNT] Self-Found Soul (Level 20)","B",81,nil,0,{"wago"},"Feats of Strength",nil,156304},
    {20136,"[DNT] Self-Found Soul (Level 30)","B",81,nil,0,{"wago"},"Feats of Strength",nil,156307},
    {20137,"[DNT] Self-Found Soul (Level 40)","B",81,nil,0,{"wago"},"Feats of Strength",nil,156310},
    {20138,"[DNT] Self-Found Soul (Level 50)","B",81,nil,0,{"wago"},"Feats of Strength",nil,156313},
    {20139,"[DNT] Self-Found Soul (Level 60)","B",81,nil,0,{"wago"},"Feats of Strength",nil,156316},
    {20193,"[DNT] Self-Found Soul (Removed Self-Found)","B",81,nil,0,{"wago"},"Feats of Strength",{{type="be_spell_target",description=nil,amount=1,asset=432417,order=1}},156405},
    {40131,"[DNT] Discoverer's Delight - Reach Level 40 in Phase 3 - Update (hidden)","B",81,nil,0,{"wago"},"Feats of Strength",{{type=5,description=nil,amount=40,asset=0,order=0}},156292},
    {40132,"[DNT] Discoverer's Delight - Reach Level 50 in Phase 3 (hidden)","B",81,nil,0,{"wago"},"Feats of Strength",{{type=5,description=nil,amount=50,asset=0,order=0}},161525},
    {40133,"[DNT] Discoverer's Delight - Reach Level 40 in Phase 3.5 - Update (hidden)","B",81,nil,0,{"wago"},"Feats of Strength",{{type=5,description=nil,amount=40,asset=0,order=0}},161527},
    {40135,"[DNT] Discoverer's Delight - Reach Level 50 in Phase 3.5 (hidden)","B",81,nil,0,{"wago"},"Feats of Strength",{{type=5,description=nil,amount=50,asset=0,order=0}},161529},
    {40137,"[DNT] Discoverer's Delight - Reach Level 50 in Phase 4 - Update (hidden)","B",81,nil,0,{"wago"},"Feats of Strength",{{type=5,description=nil,amount=50,asset=0,order=0}},156294},
    {41008,"Rune Learned - Shared Acquisition - Illari Duskfeather (40)","B",15538,nil,0,{"wago"},"Rune Discovery",{{type=74,description=nil,amount=1,asset=0,order=0}},169195},
    {41009,"Rune Learned - Shared Acquisition - Dark Riders (40)","B",15538,nil,0,{"wago"},"Rune Discovery",{{type="complete_quest",description=nil,amount=1,asset=80120,order=0}},169197},
    {41010,"Rune Learned - Shared Acquisition - Ley Lines (50)","B",15538,nil,0,{"wago"},"Rune Discovery",{{type=74,description=nil,amount=1,asset=0,order=0}},169201},
    {41011,"Rune Learned - Shared Acquisition - Wild Gods (50)","B",15538,nil,0,{"wago"},"Rune Discovery",{{type="complete_quest",description=nil,amount=1,asset=82044,order=0}},169199},
    {42133,"[DNT] Balnazzar Defeated","B",81,nil,0,{"wago"},"Feats of Strength",{{type="be_spell_target",description=nil,amount=1,asset=1235143,order=0}},210009},
    {42186,"[DNT] Balnazzar Defeated (Backup Achievement)","B",81,nil,0,{"wago"},"Feats of Strength",{{type="be_spell_target",description=nil,amount=1,asset=1235143,order=0}},210320},
} end)
