-- LibCodex-1.0 / Data / Difficulty.lua
-- Generated by tools/bake.py. 10 entries in unified row format.
-- Each row is a positional array matching the columns string below.
-- Hand-curated entries marked _handcrafted=true are preserved across bakes.

local LibCodex = LibStub("LibCodex-1.0")

LibCodex:_FeedBundledRowsLazy("Difficulty", "id,label,flags,sources,fallbackDifficultyID,instanceType,maxPlayers,minPlayers,orderIndex", function() return {
    {1,"Normal",6,{"wago"},0,1,5,5,1},
    {2,"Heroic",5,{"wago"},1,1,5,5,3},
    {3,"10 Player",2,{"wago"},0,2,10,10,1},
    {4,"25 Player",3,{"wago"},0,2,25,25,3},
    {9,"40 Player",1,{"wago"},0,2,40,40,7},
    {148,"20 Player",1,{"wago"},0,2,20,20,6},
    {173,"Normal",0,{"wago"},1,1,5,5,1},
    {174,"Heroic",1,{"wago"},2,1,5,5,3},
    {175,"10 Player",1,{"wago"},3,2,10,10,1},
    {176,"25 Player",1,{"wago"},4,2,25,25,3},
} end)
