-- LibCodex-1.0 / Data / Classes.lua
-- Generated by tools/bake.py. 15 entries in unified row format.
-- Each row is a positional array matching the columns string below.
-- Hand-curated entries marked _handcrafted=true are preserved across bakes.

local LibCodex = LibStub("LibCodex-1.0")

LibCodex:_FeedBundledRows("Classes", "id,label,token,primaryStat,sources", {
    {1,"Warrior","WARRIOR",nil,{"wago"}},
    {2,"Paladin","PALADIN",nil,{"wago"}},
    {3,"Hunter","HUNTER",nil,{"wago"}},
    {4,"Rogue","ROGUE",nil,{"wago"}},
    {5,"Priest","PRIEST",nil,{"wago"}},
    {6,"Death Knight","DEATHKNIGHT",nil,{"wago"}},
    {7,"Shaman","SHAMAN",nil,{"wago"}},
    {8,"Mage","MAGE",nil,{"wago"}},
    {9,"Warlock","WARLOCK",nil,{"wago"}},
    {10,"Monk","MONK",nil,{"wago"}},
    {11,"Druid","DRUID",nil,{"wago"}},
    {12,"Demon Hunter","DEMONHUNTER",nil,{"wago"}},
    {13,"Evoker","EVOKER",nil,{"wago"}},
    {14,"Adventurer","ADVENTURER",nil,{"wago"}},
    {15,"Traveler","TRAVELER",nil,{"wago"}},
})
