-- LibCodex-1.0 / Data / ChatChannels.lua
-- Generated by tools/bake.py. 17 entries in unified row format.
-- Each row is a positional array matching the columns string below.
-- Hand-curated entries marked _handcrafted=true are preserved across bakes.

local LibCodex = LibStub("LibCodex-1.0")

LibCodex:_FeedBundledRowsLazy("ChatChannels", "id,label,flags,sources,factionGroup,ruleset,shortcut", function() return {
    {1,"General - %s",1572875,{"wago"},0,0,"General"},
    {2,"Trade - %s",1048635,{"wago"},0,0,"Trade"},
    {22,"LocalDefense - %s",1114123,{"wago"},0,0,"LocalDefense"},
    {26,"LookingForGroup",262152,{"wago"},0,0,"LookingForGroup"},
    {27,"BigfootWorldChannel",8,{"wago"},0,0,"BigfootWorldChannel"},
    {28,"MeetingStone",8,{"wago"},0,0,"MeetingStone"},
    {32,"Newcomer Chat",14680072,{"wago"},0,1,"NewcomerChat"},
    {33,"zzOLD Shadowlands Beta Discussion",2097160,{"wago"},0,0,"ShadowlandsBetaDiscussion"},
    {34,"zzOLD Shadowlands PTR Discussion",2097160,{"wago"},0,2,"ShadowlandsPTRDiscussion"},
    {35,"Midnight Test Discussion",6291465,{"wago"},0,0,"MidnightTestDiscussion"},
    {36,"Chromie Time - Cataclysm",2097160,{"wago"},0,2,"ChromieTime"},
    {37,"Chromie Time - Burning Crusade",2097160,{"wago"},0,2,"ChromieTime"},
    {38,"Chromie Time - Wrath of the Lich King",2097160,{"wago"},0,2,"ChromieTime"},
    {39,"Chromie Time - Mists of Pandaria",2097160,{"wago"},0,2,"ChromieTime"},
    {40,"Chromie Time - Warlords of Draenor",2097160,{"wago"},0,2,"ChromieTime"},
    {41,"Chromie Time - Legion",2097160,{"wago"},0,2,"ChromieTime"},
    {42,"Trade (Services) - %s",34603067,{"wago"},0,0,"Services"},
} end)
