-- LibCodex-1.0 / Data / Languages.lua
-- Generated by tools/bake.py. 23 entries in unified row format.
-- Each row is a positional array matching the columns string below.
-- Hand-curated entries marked _handcrafted=true are preserved across bakes.

local LibCodex = LibStub("LibCodex-1.0")

LibCodex:_FeedBundledRowsLazy("Languages", "id,label,flags,sources,learningCurveID,uiTextureKitElementCount,uiTextureKitID", function() return {
    {1,"Orcish",0,{"wago"},0,0,0},
    {2,"Darnassian",0,{"wago"},0,0,0},
    {3,"Taurahe",0,{"wago"},0,0,0},
    {6,"Dwarvish",0,{"wago"},0,0,0},
    {7,"Common",0,{"wago"},0,0,0},
    {8,"Demonic",0,{"wago"},0,0,0},
    {9,"Titan",0,{"wago"},0,0,0},
    {10,"Thalassian",0,{"wago"},0,0,0},
    {11,"Draconic",0,{"wago"},0,0,0},
    {12,"Kalimag",0,{"wago"},0,0,0},
    {13,"Gnomish",0,{"wago"},0,0,0},
    {14,"Zandali",0,{"wago"},0,0,0},
    {33,"Forsaken",0,{"wago"},0,0,0},
    {35,"Draenei",0,{"wago"},0,0,0},
    {36,"Zombie",0,{"wago"},0,0,0},
    {37,"Gnomish Binary",0,{"wago"},0,0,0},
    {38,"Goblin Binary",0,{"wago"},0,0,0},
    {39,"Gilnean",0,{"wago"},0,0,0},
    {40,"Goblin",0,{"wago"},0,0,0},
    {42,"Pandaren",0,{"wago"},0,0,0},
    {43,"Pandaren",0,{"wago"},0,0,0},
    {44,"Pandaren",0,{"wago"},0,0,0},
    {168,"Rikkitun",0,{"wago"},0,0,0},
} end)
