-- LibCodex-1.0 / Data / CreatureTypes.lua
-- v2 compressed format. Generated by bake_v2/emit/module.py.
-- 15 entries, schema _V=1, _BUILD=120005.

local LibCodex = LibStub("LibCodex-1.0")

local _N = "CreatureTypes"
local _V, _BUILD = 1, 120005

LibCodex:_FeedBundledRowsV2(_N, _V, _BUILD, function() return {
    {1,"0ZZEbB94xZ"},
    {2,"0Z}6qxk.W6x(i[J"},
    {3,"0Z{Qpz/bKP"},
    {4,"0.3{pzdNQbvqC]z"},
    {5,"0.l%kzGC<U"},
    {6,"0AB2FwNP9H"},
    {7,"14WMKvqZ0$wb(Pf"},
    {8,"07g^vBAz8m"},
    {9,"0zNcnxKL^)v{%fN"},
    {10,"0-0VQaAIHkv}/K?wN>=v"},
    {11,"0-T8WwO?zE"},
    {12,"0zWMJeN@ZovQTv3p?s.G"},
    {13,"0.lWuavx%-BZ$EL"},
    {14,"16ohMwfsYWBn#pv"},
    {15,"0ypgaA=LPgx(v>?"},
} end)
